oauthClient:
  redirectUris:
    - http://127.0.0.1:5000/authorization-code/callback
  applicationType: web
trustedOrigins:
  - http://127.0.0.1:5000/

directions: |+2
  Okta configuration written to: .okta.env
  
  Install the dependencies using pip:

      pip3 install -r requirements.txt

  Run this application with:

      python3 -m flask run --port=5000
